<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT! (protoc-gen-twirp_php 0.10.0)
# source: proto/service.proto

declare(strict_types=1);

namespace App_php_golang_client_server;

/**
 * A Haberdasher makes hats for clients.
 *
 * Generated from protobuf service <code>app_php_golang_client_server.Haberdasher</code>
 */
interface Haberdasher
{
    /**
     * MakeHat produces a hat of mysterious, randomly-selected color!
     *
     * Generated from protobuf method <code>app_php_golang_client_server.Haberdasher/MakeHat</code>
     *
     * @throws \Twirp\Error
     */
    public function MakeHat(array $ctx, \App_php_golang_client_server\Size $req): \App_php_golang_client_server\Hat;
}
