<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/service.proto

namespace App_php_golang_client_server;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Size is passed when requesting a new hat to be made. It's always
 * measured in inches.
 *
 * Generated from protobuf message <code>app_php_golang_client_server.Size</code>
 */
class Size extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 inches = 1;</code>
     */
    protected $inches = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $inches
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 inches = 1;</code>
     * @return int
     */
    public function getInches()
    {
        return $this->inches;
    }

    /**
     * Generated from protobuf field <code>int32 inches = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setInches($var)
    {
        GPBUtil::checkInt32($var);
        $this->inches = $var;

        return $this;
    }

}

