<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/service.proto

namespace GPBMetadata\Proto;

class Service
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¤
proto/service.protoapp_php_golang_client_server"0
Hat
size (
color (	
name (	"
Size
inches (2_
HaberdasherP
MakeHat".app_php_golang_client_server.Size!.app_php_golang_client_server.HatB<Z:/app-php-golang-client-server;app_php_golang_client_serverbproto3'
        , true);

        static::$is_initialized = true;
    }
}

